config/routes.rb
Rails.application.routes.draw do

  root "people#index"
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
  end
end

private

def people_params
  params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/people/index.html.erb
<h1>People</h1>
<% @people.each do |person| %>
    <h2><%= person.first_name %></h2>
    <h2><%= person.last_name %></h2>
    <h2><%= person.hair_color %></h2>
    <h2><%= person.eye_color %></h2>
    <h2><%= person.gender %></h2>
    <h2><%= person.alive %></h2>
    <%= link_to 'Show Person', person_path(person) %>
<p>Find me in app/views/people/index.html.erb</p>
<% end %>

app/views/people/new.html.erb
<h1>New People</h1>
<p>Find me in app/views/people/new.html.erb</p>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_area :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.label :alive %>
  <%= f.text_field :alive %>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>

<h1><%= @person.first_name %></h1>
<h4><%= @person.last_name %></h1>
<p><%= @person.age %></p>
<p><%= @person.hair_color %></p>
<p><%= @person.eye_color %></p>
<p><%= @person.gender %></p>
<p><%= @person.alive %></p>
<%= link_to 'Back', pages_path %>